#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     lightR,              sensorLightActive)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,                     tServoStandard)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


long nLastXmitTimeStamp = nPgmTime;
long nDeltaTime         = 0;

////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Check to See if Bluetooth Link is Connected
//
////////////////////////////////////////////////////////////////////////////////////////////////////////

void checkBTLinkConnected()
{
  if (nBTCurrentStreamIndex >= 0)
    return;

  PlaySound(soundLowBuzz);
  PlaySound(soundLowBuzz);
  eraseDisplay();
  nxtDisplayCenteredTextLine(3, "BT not");
  nxtDisplayCenteredTextLine(4, "Connected");
  wait1Msec(3000);
  StopAllTasks();
}



const int kMaxSizeOfMessage = 3;
const TMailboxIDs kQueueID = mailbox1;



////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                        Receive Messages Function
//
////////////////////////////////////////////////////////////////////////////////////////////////////////

void readMultipleDataMsgs()
{
  TFileIOResult nBTCmdRdErrorStatus;
  int nSizeOfMessage;
  ubyte nRcvBuffer[kMaxSizeOfMessage];

  while (true)
  {
    // Check to see if a message is available

    nSizeOfMessage = cCmdMessageGetSize(kQueueID);
    if (nSizeOfMessage <= 0)
    {
      wait1Msec(1);    // Give other tasks a chance to run
      break;           // No more message this time
    }

    if (nSizeOfMessage > kMaxSizeOfMessage)
      nSizeOfMessage = kMaxSizeOfMessage;
    nBTCmdRdErrorStatus = cCmdMessageRead(nRcvBuffer, nSizeOfMessage, kQueueID);

    if (nRcvBuffer[0]==2){

       nMotorEncoder[motorC] = 0;
  while (nMotorEncoder[motorC] > -90)

  {

    motor[motorE] =   -30;

  }

 motor[motorE] =   0;

  servo[servo2] = 255;
  servo[servo3] = 50;
  servo[servo4] = 255;
  servo[servo5] = 128;
  servo[servo6] = 0;
  wait1Msec(4000);
  servo[servo2] = 100;
  servo[servo3] = 100;
  servo[servo4] = 100;
  servo[servo5] = 190;
  servo[servo6] = 100;
  wait1Msec(4000);

  /*nMotorEncoder[motorA] = 0;
  while(nMotorEncoder[motorA]<150){
    nMotorEncoder[motorA] = 40;
  }
  while(nMotorEncoder[motorA]>0){
    nMotorEncoder[motorA] = -40;
  }*/
  servo[servo2] = 255;
  servo[servo3] = 50;
  servo[servo4] = 255;
  servo[servo5] = 128;
  servo[servo6] = 0;
  wait1Msec(4000);
  //servo[servo2] = 0;

 // servo[servo2] = 0;
  //servo[servo2] = 0;

 // servo[servo2] = 0;

   nMotorEncoder[motorC] = 0;
  while (nMotorEncoder[motorC] < 90)

  {

    motor[motorE] =   30;

  }

  motor[motorE] =   0;

    }

  }
  return;
}


task main()
{
  bNxtLCDStatusDisplay = true;
  wait10Msec(10);
  while(true){
    checkBTLinkConnected();
    readMultipleDataMsgs();
    wait1Msec(1);
  }

  return;
}
