#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     lightR,              sensorLightActive)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,                     tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 /* nMotorEncoder[motorC] = 0;
  while (nMotorEncoder[motorC] > -90)

  {

    motor[motorE] =  -100;

  }

  motor[motorD] =  -40;*/

  servo[servo1] = 30;
  servo[servo2] = 100;
  servo[servo3] = 0;
  servo[servo4] = 255;
  //servo[servo5] = 0;
  wait1Msec(10000);
  servo[servo1] = 90;
  servo[servo2] = 30;
  servo[servo3] = 110;
  servo[servo4] = 100;
  //servo[servo5] = 255;

  wait1Msec(10000);

 // servo[servo2] = 0;



}
