#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MAXMOTORSPEED 50

const float cosVal[3] = {0, -1, 0};
const float sinVal[3] = {1, 0, -1};

int round(float f)
{
  return (f>0)?(int)(f+0.5):(int)(f - 0.5);
}

void getMotorSpeeds(int &motorSpeedD, int &motorSpeedE, int &motorSpeedF, int &motorSpeedG, int angle, int Vb) {
  float Vw1, Vw2, Vw3, Vw4, norm_factor;

  Vw1 = Vb*cosDegrees(angle);
  Vw2 = Vb*(cosVal[0]*cosDegrees(angle) + sinVal[0]*sinDegrees(angle));
  Vw3 = Vb*(cosVal[1]*cosDegrees(angle) + sinVal[1]*sinDegrees(angle));
  Vw4 = Vb*(cosVal[2]*cosDegrees(angle) + sinVal[2]*sinDegrees(angle));

  norm_factor = 1.0;

  if (Vw1 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw1;
  } else if (Vw2 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw2;
  } else if (Vw3 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw3;
  } else if (Vw4 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw4;
  }

  motorSpeedD = round(Vw1 * norm_factor);
  motorSpeedE = round(Vw2 * norm_factor);
  motorSpeedF = round(Vw3 * norm_factor);
  motorSpeedG = round(Vw4 * norm_factor);
}


task main()
{
  int mSD, mSE, mSF, mSG;
   getMotorSpeeds(mSD, mSE, mSF, mSG, 213, 25);
   motor[motorD] = mSD;   // Motor D is run at a power level of 25.
   motor[motorE] = mSE;
   motor[motorF] = mSF;
   motor[motorG] = mSG;// Motor E is run at a power level of 25.
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
   getMotorSpeeds(mSD, mSE, mSF, mSG, 270, 25);
   motor[motorD] = mSD;   // Motor D is run at a power level of 25.
   motor[motorE] = mSE;
   motor[motorF] = mSF;
   motor[motorG] = mSG;// Motor E is run at a power level of 25.
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
   getMotorSpeeds(mSD, mSE, mSF, mSG, 323, 25);
   motor[motorD] = mSD;   // Motor D is run at a power level of 25.
   motor[motorE] = mSE;
   motor[motorF] = mSF;
   motor[motorG] = mSG;// Motor E is run at a power level of 25.
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
   getMotorSpeeds(mSD, mSE, mSF, mSG, 270, 25);
   motor[motorD] = mSD;   // Motor D is run at a power level of 25.
   motor[motorE] = mSE;
   motor[motorF] = mSF;
   motor[motorG] = mSG;// Motor E is run at a power level of 25.
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
}
