#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     HTMC,                sensorLowSpeed)
#pragma config(Sensor, S3,     ultra,               sensorSONAR)
#pragma config(Sensor, S4,     fultra,               sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/HTMC-driver.h"

bool new;
ubyte nMessage[17];

void checkBTLinkConnected();
void readMessages();

#define MAXMOTORSPEED 50
int _target = 0;


int round(float f)
{
  return (f>0)?(int)(f+0.5):(int)(f - 0.5);
}

void runMotorSpeeds(int &motorSpeedD, int &motorSpeedE, int &motorSpeedF, int &motorSpeedG, int angle, int Vb) {
  float Vw1, Vw2, Vw3, Vw4, norm_factor;

  Vw1 = Vb*cosDegrees(angle);
  Vw2 = Vb*sinDegrees(angle);
  Vw3 = -Vw1;
  Vw4 = -Vw2;

  norm_factor = 1.0;

  if (Vw1 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw1;
  } else if (Vw2 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw2;
  } else if (Vw3 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw3;
  } else if (Vw4 > MAXMOTORSPEED) {
    norm_factor = MAXMOTORSPEED / Vw4;
  }

  motorSpeedD = round(Vw1 * norm_factor);
  motorSpeedE = round(Vw2 * norm_factor);
  motorSpeedF = round(Vw3 * norm_factor);
  motorSpeedG = round(Vw4 * norm_factor);

  motor[motorD] = motorSpeedD;
  motor[motorE] = motorSpeedE;
  motor[motorF] = motorSpeedF;
  motor[motorG] = motorSpeedG;
}

void stopMotors()
{
  motor[motorD] = 0;
  motor[motorE] = 0;
  motor[motorF] = 0;
  motor[motorG] = 0;
}

void fixpassy()
{
  while(HTMCreadRelativeHeading(HTMC) > 0){
     motor[motorD] = 20;
     motor[motorE] = -20;
     motor[motorF] = 20;
     motor[motorG] = -20;
   }
   stopMotors();
   while(HTMCreadRelativeHeading(HTMC) < 0){
     motor[motorD] = -20;
     motor[motorE] = 20;
     motor[motorF] = -20;
     motor[motorG] = 20;
   }
   stopMotors();
 }


task main()
{


  HTMCsetTarget(HTMC);

	while(true){
	   checkBTLinkConnected();
	   readMessages();






 /*
   runMotorSpeeds(mSD, mSE, mSF, mSG, 213, 25);
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
   runMotorSpeeds(mSD, mSE, mSF, mSG, 270, 25);
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
   runMotorSpeeds(mSD, mSE, mSF, mSG, 323, 25);
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
   runMotorSpeeds(mSD, mSE, mSF, mSG, 270, 25);
   wait1Msec(4000);       // The program waits 4000 milliseconds (4 seconds) before running further code
   stopMotors();

     while(HTMCreadRelativeHeading(HTMC) > 0){
     motor[motorD] = 20;
     motor[motorE] = -20;
     motor[motorF] = 20;
     motor[motorG] = -20;
   }
   while(HTMCreadRelativeHeading(HTMC) < 0){
     motor[motorD] = -20;
     motor[motorE] = 20;
     motor[motorF] = -20;
     motor[motorG] = 20;
   }*/
}
}


////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                        Receive Messages
////////////////////////////////////////////////////////////////////////////////////////////////////////

void readMessages()
{


int mSD, mSE, mSF, mSG;


	  cCmdMessageRead(nMessage, 1, mailbox1);



	  if(nMessage[0] == 1){

	  while(SensorValue(ultra) > 25){
	     runMotorSpeeds(mSD, mSE, mSF, mSG, 213, 25);
	  }
	  stopMotors();
	  fixpassy();

	  while(SensorValue(fultra) > 40) {

	  runMotorSpeeds(mSD, mSE, mSF, mSG, 270, 25);
	}
	stopMotors();
	fixpassy();
}

	if(nMessage[0] == 2){

	    while(SensorValue(ultra) < 35){
	      runMotorSpeeds(mSD, mSE, mSF, mSG, 323, 25);
	  }
	  stopMotors();
	  fixpassy();

	  while(SensorValue(fultra) > 40) {

	  runMotorSpeeds(mSD, mSE, mSF, mSG, 270, 25);
	}
	stopMotors();
	fixpassy();
	}



	if(nMessage[0] == 3){

	   while(SensorValue(fultra) > 50) {

	  runMotorSpeeds(mSD, mSE, mSF, mSG, 270, 25);
	}

	stopMotors();

	fixpassy();


	}

	//ubyte krik = 1;

 //cCmdMessageWriteToBluetooth(0,krik,1,mailbox1);



}


////////////////////////////////////////////////////////////////////////////////////////////////////////

void checkBTLinkConnected()
{
	if (nBTCurrentStreamIndex >= 0)
	  return;

	PlaySound(soundLowBuzz);
	PlaySound(soundLowBuzz);
	eraseDisplay();
	nxtDisplayCenteredTextLine(3, "BT not");
	nxtDisplayCenteredTextLine(4, "Connected");
	wait1Msec(3000);
	StopAllTasks();
}
